:global:
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
.travis.yml:
  sudo: true
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: Fl+OcYDQINDadl6DPcYHk4RwKXO/CjsdtqxAAqaullF7Tu6Jwwltapp00CUSFSdgbu7ena5FfUGNhq9at1xDJDlQq/nX3qZOBs97qI6Uy5M10+a6WXCrDmiE0yxZPMZCdn4+1ll9egwNFMfbc0U9YTohYyA4FHpGulc2hrm/BTdsIePqejNDWTSaxnIB5EnN65C8wEuXQkxo5hKt6Cmdh1XkiMc7/03hbtqVqiAqgwZ6xXVJ7XodrrF0TB37xZtm606ivP7psAx4a9QmdwxEB9vnt80zuxkkeCi2XIwsaig6nl5yZ06pUGDYVGMSSBDq467AFKBg6LHGhf76Fv0aJ5bCEedtPRlfzfbtLlyGzmbXAP6oAme5jCLnVt/baBCypRwIQf6+8plpc2N8dyyjQqTrKiVT+6pea0D/iee2rgrgK09WqAfEpaEymz1if1SeL2F4/NxbRNm79AecpIbuR0NdOyJo6HKH+aTkSdxfLHm3UwaqvWhZUmDbviDpy9oeMIp6hjrJlmxYs8EpkNbbld2w8b2iUcbvXNuAaB39SsSTAvHPbbh3ovuNpsbJ8aaoI5ajctEktTBtA28/KXd0gBlpB1Q9XHlPphvtKtY0MYYFkEulS2CZxVIcGmzlbCRkk+8a9WAQYNtPZoG/yam7c/2asSB3a/gk2GYktfkIvog=
    api_key:
      secure: WC1G4sdWUZLKtSg4IhXp6VWIAxOwPS7ovdv9LTlzh0x4Jd/7Gms+ZtXptjNJ7njyhniJTStFH6ee6081OfmKYZYja5BV7NQXO1uFmo0g6ZVGjOw8FOwERiv9wc4vvPGxKKB4ZxFytupPRFm9MOX+0o8YwsXqaC+i6NvMS/5vxmZ/Ou0APuC70dcC3fC6nAm7XmweGzs3yFAGrz0LtF+G/BK2dCYNZt1iub1ioV2RIUkMZ522Too5pSMoPXFiA1IDNT+ZUO+yvITYW8Ya2vMFCQ2okE08yBz27zvGlKogIC+AYnRkfKleHwt8daF6bJ0inkIrYhnXVscI7SsS8dR1qhhnFyfK9cHCV/5d5BqXMOl5Rtw/4zGg9tlue0dQDUxn/uzgJidlbVlsQbj45JW2VonuXln9j3yOPmKGWPRCg5LPjIlQdr8BEMVh6V5vPJHlmSxFChj5OXq+duka6Ig8NecuWuqsEJorMjg656oaqnjn03lVyiCY80CpttO5OPxHBSgaiPPjEnZ9Ofx/nafVjhK5lSQTZD1hB8Z/3C7Pk96VnDFB8yz6tPYBeTDJVoktwUP2wFQ6rtQYqe2KjEhDr0GBayFyZNnhLi7p42hiSopsDaxhsqMyGUzMLdoixkec+2Ve5khoV6eFyIeMYzzpzfUo4VdJ7+zXPg4jZv/xFZc=

