:global:
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
.travis.yml:
  sudo: true
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: nU3Ca+UUtUEbEGHFsiPId72dA14mWhQxewhyGJsoIbb9oYevMTUcHFK0Bv2cBL0WcLhWW8UgDtFQWUXVibSAfFztyR+KO0ACrNUAxRN1k37K4lpaw3kkiWsTPT9b8XYG0EmnlnbMSyF6Y+faG7uEXmdXIT65f65CRmNYdgZH3RJgjXBQq0Jlh2Ax96Z7kZim2JQAOplyRC+UxGNLuKYf+hNTJhdNvkFYoW0suTSHfkaXmQm4YrBUY95HeEW4gDQ3ZbqCBeDFHK/qqE97WelAKLZVm7Lux2T6lRHcFILLHalG9F70wobN1B9my4xEHxkM5gqvjvp6KWWGzEW56Eu+THHX0Bi8XjPDhuxckfrgcITfhXoeHeJvE67FOOOlhCFbqwoM0+/X2LTrA9Lycm2Q4kI4C+vadPdaNmK4MJQLzkVDorb6yAQJeIg7mw7NowvaNP9mspi8J+X0XrLtJxNsHKzP8GtX1d/9AP1JJYgjJg7Vf0LsW3nAwPQ5wvjzW0R5WS06hl/B0yYHMkGTUfSoJQ48M6RlndQeanrocfIU5dGjJsmB6Sazq/L+kVZM7L5cLpzm8BkLl3O+fHkuAM4Yds7Xm7eJCe/uXqwAHZtNf7Pu96DqPCKtp7buEdRrEPoWKgGFLy0J6XuUwFRPhrsfyOmmDzapN5Xdl08NvqT4QIM=
    api_key:
      secure: IIj+xJxifiTcXAwyKgdoIyZad0LmB2S9dpZ38PPstzPhCQ9mF8vO4sCbm0shbzo+MBARYgrvKHelaVxRRJRDO4v2AnExFsFBWAVUOJ6leUy0ncWJU71M1uhWX3CYUwm4AluOFCwCbhayheXlDhNSbHVRcNidlg85NdnatP9zlot8IqlDouTipErnOI6fG3RosVxqhvWYmcZY4PuCxp/PkFw6NNjzEWGz4qbF3P4RmOAFjrIPTUrcVlMe9gehhtuZCiZUi6wo5mf73CaDh2wN0Dr+u0wvUilsVF3pHWf6lagF51pciEN1Q+hEUCm+8YN+HhBaUlqrx+Kz9EjUXQUDSVn2JFv40pnFrX1PMoL8F4eyIGZSeuZ9FxAGaM3batsvKr3VNaQb4dBHiRPFciCCi0UsgPW4Uu/yhZTPgNf8BH93RHV6E0yOVy3EztgcjtcqCxoveqOkR7qTWmQXbN6mWCU+Vvwjcme6fN10n7CpTsITtx/IfLPd9vZmX7glhW3hY3a6wQA9bqv3RsD5lFKbmXTVpjdrzdbagYTCdw+NaFCvs/kG8sMm0oeUwXqe7WRvLSCG3/yQGfNR34+n2zGh1U7nb3sv181s9vPhkh5WL/LhXH316gX7X224uvnaI74ePCIbrTRSuNL7JM4Pg4zi4cE51/2VRtEWrnw9uyG3Ezs=

